version: "3.8"

services:
  nats:
    image: nats
    command: -c nats.conf
    ports:
      - "8222:8222"
      - "6222:6222"
      - "4222:4222"
    networks: ["app-network"]
networks:
  app-network:
    name: app-network
    driver: bridge
